version: "3.8"
services:
    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        ports:
            - target: 5000
              published: ${SERVER_PORT:-5000}
              protocol: tcp
              mode: host
    front:
        build:
            context: .
            dockerfile: front/Dockerfile
        ports:
            - target: 3000
              published: ${FRONT_PORT:-3000}
              protocol: tcp
              mode: host
 