version: "3.8"
services:
    server:
        build:
            context: ./server
        ports:
            - target: 5000
              published: ${SERVER_PORT:-5000}
              protocol: tcp
              mode: host
    front:
        build:
            context: ./front
        ports:
            - target: 3000
              published: ${FRONT_PORT:-3000}
              protocol: tcp
              mode: host
 